version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
  webserver:
    image: apache/airflow:2.1.0
    environment:
      AIRFLOW_CORE_EXECUTOR: LocalExecutor
      AIRFLOW_CORE_SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW_CORE_FERNET_KEY: "YOUR_FERNET_KEY"
      AIRFLOW_CORE_LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: webserver
  scheduler:
    image: apache/airflow:2.1.0
    environment:
      AIRFLOW_CORE_EXECUTOR: LocalExecutor
      AIRFLOW_CORE_SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW_CORE_FERNET_KEY: "YOUR_FERNET_KEY"
      AIRFLOW_CORE_LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
    depends_on:
      - postgres
    command: scheduler
